/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SorteoRouteImport } from './routes/sorteo'
import { Route as PremiosRouteImport } from './routes/premios'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PencaRouteImport } from './routes/penca'
import { Route as HistoriaRouteImport } from './routes/historia'
import { Route as GaleriaRouteImport } from './routes/galeria'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'

const SorteoRoute = SorteoRouteImport.update({
  id: '/sorteo',
  path: '/sorteo',
  getParentRoute: () => rootRouteImport,
} as any)
const PremiosRoute = PremiosRouteImport.update({
  id: '/premios',
  path: '/premios',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PencaRoute = PencaRouteImport.update({
  id: '/penca',
  path: '/penca',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoriaRoute = HistoriaRouteImport.update({
  id: '/historia',
  path: '/historia',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaRoute = GaleriaRouteImport.update({
  id: '/galeria',
  path: '/galeria',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendario': typeof CalendarioRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/penca': typeof PencaRoute
  '/perfil': typeof PerfilRoute
  '/premios': typeof PremiosRoute
  '/sorteo': typeof SorteoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendario': typeof CalendarioRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/penca': typeof PencaRoute
  '/perfil': typeof PerfilRoute
  '/premios': typeof PremiosRoute
  '/sorteo': typeof SorteoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/calendario': typeof CalendarioRoute
  '/galeria': typeof GaleriaRoute
  '/historia': typeof HistoriaRoute
  '/penca': typeof PencaRoute
  '/perfil': typeof PerfilRoute
  '/premios': typeof PremiosRoute
  '/sorteo': typeof SorteoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/calendario'
    | '/galeria'
    | '/historia'
    | '/penca'
    | '/perfil'
    | '/premios'
    | '/sorteo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/calendario'
    | '/galeria'
    | '/historia'
    | '/penca'
    | '/perfil'
    | '/premios'
    | '/sorteo'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/calendario'
    | '/galeria'
    | '/historia'
    | '/penca'
    | '/perfil'
    | '/premios'
    | '/sorteo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  CalendarioRoute: typeof CalendarioRoute
  GaleriaRoute: typeof GaleriaRoute
  HistoriaRoute: typeof HistoriaRoute
  PencaRoute: typeof PencaRoute
  PerfilRoute: typeof PerfilRoute
  PremiosRoute: typeof PremiosRoute
  SorteoRoute: typeof SorteoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sorteo': {
      id: '/sorteo'
      path: '/sorteo'
      fullPath: '/sorteo'
      preLoaderRoute: typeof SorteoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/premios': {
      id: '/premios'
      path: '/premios'
      fullPath: '/premios'
      preLoaderRoute: typeof PremiosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penca': {
      id: '/penca'
      path: '/penca'
      fullPath: '/penca'
      preLoaderRoute: typeof PencaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/historia': {
      id: '/historia'
      path: '/historia'
      fullPath: '/historia'
      preLoaderRoute: typeof HistoriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria': {
      id: '/galeria'
      path: '/galeria'
      fullPath: '/galeria'
      preLoaderRoute: typeof GaleriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  CalendarioRoute: CalendarioRoute,
  GaleriaRoute: GaleriaRoute,
  HistoriaRoute: HistoriaRoute,
  PencaRoute: PencaRoute,
  PerfilRoute: PerfilRoute,
  PremiosRoute: PremiosRoute,
  SorteoRoute: SorteoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
